Fixing and checking the usage.log file

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -31,7 +31,7 @@ jobs:
             npm install -g @railway/cli
 
       - run:
-          name: Deploy + Monitor Railway
+          name: Deploy & Monitor Railway
           environment:
             RAILWAY_TOKEN: b3f08ed2-38e9-4d90-beb4-e66080321082
           command: |
@@ -40,15 +40,17 @@ jobs:
             railway up --service fab5a752-14e9-4e05-9f95-4499ed6e7cd4 -d > railway.log 2>&1 &
             APP_PID=$!
 
-            echo "Railway PID: $APP_PID"
+            sleep 2
 
-            pidstat -r -u -p $APP_PID 1 > usage.log &
+            echo "Railway PID: $APP_PID"
+            ps -p $APP_PID || echo "Railway PID not found"
+            cat railway.log || echo "No output from Railway"
+
+            pidstat -r -u -p $APP_PID 1 30 > usage.log &
             PIDSTAT_PID=$!
 
             wait $APP_PID
             kill $PIDSTAT_PID || true
-
-            echo "PIDSTAT_PID=$PIDSTAT_PID" >> $BASH_ENV
 
       - run:
           name: Stop Monitoring & Measure End Time
@@ -63,14 +65,8 @@ jobs:
             echo "=============================="
 
       - run:
-          name: Tes pidstat dengan proses dummy
-          command: |
-            sleep 10 &
-            DUMMY_PID=$!
-            pidstat -r -u -p $DUMMY_PID 1 5 > dummy-usage.log
-            cat dummy-usage.log
-
-
+          name: Checking usage.log file
+          command: cat usage.log
 
       - store_artifacts:
           path: usage.log
